import { ActivityCategoryEntity } from '../../domain/entities/activity-category.entity.js';

export const ACTIVITY_CATEGORY_SEEDS: Partial<ActivityCategoryEntity>[] = [
  {
    id: 'predicacion',
    name: 'Predicacion',
    color: '#1e40af',
    bgColor: '#eff6ff',
    borderColor: '#3b82f6',
    sortOrder: 0,
    subcategories: [
      {
        id: 'campanas',
        name: 'Campanas',
        unit: 'noches',
        hasHours: false,
        description: 'Predicaciones de usualmente 6 dias cada noche',
      },
      {
        id: 'estudios_biblicos',
        name: 'Estudios Biblicos',
        unit: 'cantidad',
        hasHours: false,
        description: 'Medido en cantidad',
      },
      {
        id: 'predicas',
        name: 'Predicas',
        unit: 'cantidad',
        hasHours: false,
        description: 'Medido en cantidad',
      },
      {
        id: 'servicios_funebres',
        name: 'Servicios Funebres',
        unit: 'cantidad',
        hasHours: false,
        description: 'Medido en cantidad',
      },
    ],
  },
  {
    id: 'ensenanza',
    name: 'Ensenanza',
    color: '#4338ca',
    bgColor: '#eef2ff',
    borderColor: '#6366f1',
    sortOrder: 1,
    subcategories: [
      {
        id: 'seminarios',
        name: 'Seminarios',
        unit: 'cantidad',
        hasHours: false,
        description: 'Medido en cantidad',
      },
      {
        id: 'congresos',
        name: 'Congresos',
        unit: 'dias',
        hasHours: false,
        description: 'Medido en dias',
      },
      {
        id: 'discipulados',
        name: 'Discipulados',
        unit: 'cantidad',
        hasHours: false,
        description: 'Medido en cantidad',
      },
      {
        id: 'clubes_juveniles',
        name: 'Clubes Juveniles',
        unit: 'cantidad',
        hasHours: false,
        description: 'Medido en cantidad',
      },
      {
        id: 'juntas_reuniones',
        name: 'Juntas y Reuniones en Iglesias',
        unit: 'cantidad',
        hasHours: false,
        description: 'Medido en cantidad',
      },
    ],
  },
  {
    id: 'servicio',
    name: 'Servicio',
    color: '#dc2626',
    bgColor: '#fef2f2',
    borderColor: '#ef4444',
    sortOrder: 2,
    subcategories: [
      {
        id: 'consejeria',
        name: 'Consejeria',
        unit: 'cantidad',
        hasHours: false,
        description: 'Medido en cantidad',
      },
      {
        id: 'exposalud',
        name: 'Exposalud',
        unit: 'cantidad',
        hasHours: false,
        description: 'Medido en cantidad',
      },
      {
        id: 'impacto_comunidad',
        name: 'Impacto a la Comunidad',
        unit: 'cantidad',
        hasHours: false,
        description: 'Medido en cantidad',
      },
      {
        id: 'obra_social',
        name: 'Obra Social',
        unit: 'cantidad',
        hasHours: false,
        description: 'Medido en cantidad',
      },
      {
        id: 'repartir_mercados',
        name: 'Repartir Mercados y Literaturas',
        unit: 'cantidad',
        hasHours: false,
        description: 'Medido en cantidad',
      },
    ],
  },
  {
    id: 'confraternidad',
    name: 'Confraternidad',
    color: '#15803d',
    bgColor: '#f0fdf4',
    borderColor: '#22c55e',
    sortOrder: 3,
    subcategories: [
      {
        id: 'visitacion',
        name: 'Visitacion',
        unit: 'veces',
        hasHours: true,
        description: 'Horas o por veces',
      },
      {
        id: 'grupos_pequenos',
        name: 'Grupos Pequenos',
        unit: 'veces',
        hasHours: true,
        description: 'Horas o por veces diarias',
      },
      {
        id: 'recepcion_sabado',
        name: 'Recepcion de Sabado',
        unit: 'veces',
        hasHours: false,
        description: 'Veces diarias',
      },
      {
        id: 'integracionistas',
        name: 'Integracionistas con la Hermandad',
        unit: 'veces',
        hasHours: false,
        description: 'Veces diarias',
      },
    ],
  },
  {
    id: 'adoracion',
    name: 'Adoracion',
    color: '#ea580c',
    bgColor: '#fff7ed',
    borderColor: '#f97316',
    sortOrder: 4,
    subcategories: [
      {
        id: 'estudio_personal',
        name: 'Horas de Estudio Personal',
        unit: 'horas',
        hasHours: false,
        description: 'Medido en horas',
      },
      {
        id: 'vigilias',
        name: 'Vigilias',
        unit: 'veces',
        hasHours: true,
        description: 'Veces y horas dedicadas',
      },
      {
        id: 'ayunos',
        name: 'Ayunos',
        unit: 'veces',
        hasHours: false,
        description: 'Veces diarias',
      },
      {
        id: 'conciertos_musicales',
        name: 'Conciertos Musicales',
        unit: 'veces',
        hasHours: false,
        description: 'Veces diarias',
      },
      {
        id: 'cena_senor',
        name: 'Cena del Senor',
        unit: 'veces',
        hasHours: false,
        description: 'Veces diarias',
      },
    ],
  },
  {
    id: 'reproduccion',
    name: 'Reproduccion',
    color: '#7c3aed',
    bgColor: '#f5f3ff',
    borderColor: '#8b5cf6',
    sortOrder: 5,
    subcategories: [
      {
        id: 'organizar_iglesia',
        name: 'Proceso para Organizar Nueva Iglesia',
        unit: 'veces',
        hasHours: true,
        description: 'Horas o veces diarias',
      },
      {
        id: 'bautismos',
        name: 'Cantidad de Bautismos',
        unit: 'cantidad',
        hasHours: false,
        description: 'Bautismos registrados',
      },
    ],
  },
  {
    id: 'transporte',
    name: 'Transporte',
    color: '#475569',
    bgColor: '#f8fafc',
    borderColor: '#94a3b8',
    sortOrder: 6,
    subcategories: [
      {
        id: 'transporte',
        name: 'Transporte',
        unit: 'horas',
        hasHours: false,
        description:
          'Horas de transporte y gasto en COP. Permite subir evidencia (recibos, fotos).',
      },
    ],
  },
];
